# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'srplauncher-final.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys
import webbrowser
import urllib3
import os
import pysvn
import img

svnDir = "C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\\addons\Santos"
srpsrv = None

srpsvn = pysvn.Client()


if not os.path.exists('svninfo.txt'):
    svnFile = open('svninfo.txt', 'w+')
    svnFile = svnFile.readline()
else:
    svnFile = open('svninfo.txt', 'r+')
    svnFile = svnFile.readline()


if svnFile == "":
    pass
else:
    svnDir = svnFile
    print (svnDir)


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SantosRP(QtGui.QMainWindow):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)

        # vw = QtGui.QAction("View website", self)
        # self.statusBar()
        #
        # mainMenu = self.menuBar()
        # fileMenu = mainMenu.addMenu('&File')
        # fileMenu.addAction(vw)


    def setupUi(self, SantosRP):
        SantosRP.setObjectName(_fromUtf8("SantosRP"))
        SantosRP.resize(400, 435)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SantosRP.sizePolicy().hasHeightForWidth())
        SantosRP.setSizePolicy(sizePolicy)
        SantosRP.setMinimumSize(QtCore.QSize(380, 435))
        SantosRP.setMaximumSize(QtCore.QSize(380, 435))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setBold(False)
        font.setWeight(50)
        SantosRP.setFont(font)
        SantosRP.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        SantosRP.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SantosRP.setWindowIcon(icon)
        SantosRP.setAutoFillBackground(False)
        SantosRP.setStyleSheet(_fromUtf8("background-color:#1b1e25;color:#FFF;QToolButton{color:#000;}"))
        self.layoutWidget = QtGui.QWidget(SantosRP)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 310, 488, 27))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(36, -1, 35, -1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_play = QtGui.QPushButton(self.layoutWidget)
        self.btn_play.setMinimumSize(QtCore.QSize(77, 25))
        self.btn_play.setMaximumSize(QtCore.QSize(77, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 144, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 144, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 144, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 144, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 144, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 144, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 144, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 144, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 144, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_play.setPalette(palette)
        self.btn_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play.setAccessibleDescription(_fromUtf8(""))
        self.btn_play.setAutoFillBackground(False)
        self.btn_play.setStyleSheet(_fromUtf8("background-color:#5c90d2;border:none;"))
        self.btn_play.setFlat(False)
        self.btn_play.setObjectName(_fromUtf8("btn_play"))
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_joinTS = QtGui.QPushButton(self.layoutWidget)
        self.btn_joinTS.setMinimumSize(QtCore.QSize(77, 25))
        self.btn_joinTS.setMaximumSize(QtCore.QSize(77, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 138, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 138, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 138, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 138, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 138, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 138, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 138, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 138, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 138, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_joinTS.setPalette(palette)
        self.btn_joinTS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_joinTS.setAccessibleDescription(_fromUtf8(""))
        self.btn_joinTS.setAutoFillBackground(False)
        self.btn_joinTS.setStyleSheet(_fromUtf8("background-color:#a48ad4;border:none;"))
        self.btn_joinTS.setFlat(False)
        self.btn_joinTS.setObjectName(_fromUtf8("btn_joinTS"))
        self.horizontalLayout.addWidget(self.btn_joinTS)
        self.btn_update = QtGui.QPushButton(self.layoutWidget)
        self.btn_update.setMinimumSize(QtCore.QSize(77, 25))
        self.btn_update.setMaximumSize(QtCore.QSize(77, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 180, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 180, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 180, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 180, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 180, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 180, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 180, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 180, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 180, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_update.setPalette(palette)
        self.btn_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_update.setAutoFillBackground(False)
        self.btn_update.setStyleSheet(_fromUtf8("background-color:#44b456;border:none;"))
        self.btn_update.setObjectName(_fromUtf8("btn_update"))
        self.horizontalLayout.addWidget(self.btn_update)
        self.btn_lh = QtGui.QPushButton(self.layoutWidget)
        self.btn_lh.setMinimumSize(QtCore.QSize(77, 25))
        self.btn_lh.setMaximumSize(QtCore.QSize(77, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_lh.setPalette(palette)
        self.btn_lh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_lh.setAutoFillBackground(False)
        self.btn_lh.setStyleSheet(_fromUtf8("background-color:#666;border:none;"))
        self.btn_lh.setObjectName(_fromUtf8("btn_lh"))
        self.horizontalLayout.addWidget(self.btn_lh)
        self.btn_play.raise_()
        self.btn_lh.raise_()
        self.btn_update.raise_()
        self.btn_joinTS.raise_()
        self.logo = QtGui.QLabel(SantosRP)
        self.logo.setGeometry(QtCore.QRect(50, 62, 291, 131))
        self.logo.setText(_fromUtf8(""))
        self.logo.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/logo.png")))
        self.logo.setObjectName(_fromUtf8("logo"))
        self.layoutWidget1 = QtGui.QWidget(SantosRP)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 221, 401, 22))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setContentsMargins(35, -1, 35, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.desiredserver = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.desiredserver.setFont(font)
        self.desiredserver.setStyleSheet(_fromUtf8("color:#FFF;"))
        self.desiredserver.setObjectName(_fromUtf8("desiredserver"))
        self.horizontalLayout_3.addWidget(self.desiredserver)
        self.radio_eu = QtGui.QRadioButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_eu.sizePolicy().hasHeightForWidth())
        self.radio_eu.setSizePolicy(sizePolicy)
        self.radio_eu.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_eu.setFont(font)
        self.radio_eu.setStyleSheet(_fromUtf8("color:#FFF;"))
        self.radio_eu.setObjectName(_fromUtf8("radio_eu"))
        self.horizontalLayout_3.addWidget(self.radio_eu)
        self.radio_us = QtGui.QRadioButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_us.sizePolicy().hasHeightForWidth())
        self.radio_us.setSizePolicy(sizePolicy)
        self.radio_us.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_us.setFont(font)
        self.radio_us.setStyleSheet(_fromUtf8("color:#FFF;"))
        self.radio_us.setObjectName(_fromUtf8("radio_us"))
        self.horizontalLayout_3.addWidget(self.radio_us)
        self.layoutWidget2 = QtGui.QWidget(SantosRP)
        self.layoutWidget2.setGeometry(QtCore.QRect(2, 277, 401, 27))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_4.setContentsMargins(35, -1, 35, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.filepath = QtGui.QLineEdit(self.layoutWidget2)
        self.filepath.setMinimumSize(QtCore.QSize(280, 25))
        self.filepath.setText(svnDir)
        self.filepath.setReadOnly(True)
        self.filepath.setStyleSheet(_fromUtf8("color:#FFF;border:1px solid #666;"))
        self.filepath.setPlaceholderText(_fromUtf8(""))
        self.filepath.setObjectName(_fromUtf8("filepath"))
        self.horizontalLayout_4.addWidget(self.filepath)
        self.fileselect = QtGui.QToolButton(self.layoutWidget2)
        self.fileselect.setMinimumSize(QtCore.QSize(25, 25))
        self.fileselect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fileselect.setStyleSheet(_fromUtf8("background-color:#FFF;color:#000;border:1px solid #000;"))
        self.fileselect.setObjectName(_fromUtf8("fileselect"))
        self.horizontalLayout_4.addWidget(self.fileselect)
        self.layoutWidget3 = QtGui.QWidget(SantosRP)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 370, 401, 34))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(35, -1, 35, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.credits1 = QtGui.QLabel(self.layoutWidget3)
        self.credits1.setMinimumSize(QtCore.QSize(291, 0))
        self.credits1.setMaximumSize(QtCore.QSize(291, 16777215))
        self.credits1.setStyleSheet(_fromUtf8("color:#FFF;"))
        self.credits1.setAlignment(QtCore.Qt.AlignCenter)
        self.credits1.setObjectName(_fromUtf8("credits1"))
        self.verticalLayout.addWidget(self.credits1)
        self.credits2 = QtGui.QLabel(self.layoutWidget3)
        self.credits2.setMinimumSize(QtCore.QSize(291, 0))
        self.credits2.setMaximumSize(QtCore.QSize(291, 16777215))
        self.credits2.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.credits2.setAlignment(QtCore.Qt.AlignCenter)
        self.credits2.setOpenExternalLinks(True)
        self.credits2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.credits2.setObjectName(_fromUtf8("credits2"))
        self.verticalLayout.addWidget(self.credits2)
        self.layoutWidget_2 = QtGui.QWidget(SantosRP)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 245, 401, 32))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_5.setContentsMargins(35, -1, 35, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.Players = QtGui.QLabel(self.layoutWidget_2)
        self.Players.setMinimumSize(QtCore.QSize(50, 15))
        self.Players.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Players.setFont(font)
        self.Players.setStyleSheet(_fromUtf8("color:#FFF;"))
        self.Players.setObjectName(_fromUtf8("Players"))
        self.horizontalLayout_5.addWidget(self.Players)
        self.playercount = QtGui.QLabel(self.layoutWidget_2)
        self.playercount.setMinimumSize(QtCore.QSize(50, 15))
        self.playercount.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.playercount.setFont(font)
        self.playercount.setStyleSheet(_fromUtf8("color:#FFF;"))
        self.playercount.setText(_fromUtf8(""))
        self.playercount.setObjectName(_fromUtf8("playercount"))
        self.horizontalLayout_5.addWidget(self.playercount)



        self.retranslateUi(SantosRP)
        QtCore.QMetaObject.connectSlotsByName(SantosRP)

    def retranslateUi(self, SantosRP):
        SantosRP.setWindowTitle(_translate("SantosRP", "SantosRP - Launcher (lite)", None))
        self.btn_play.setText(_translate("SantosRP", "Play", None))
        self.btn_joinTS.setText(_translate("SantosRP", "Join TS", None))
        self.btn_update.setText(_translate("SantosRP", "Update", None))
        self.btn_lh.setText(_translate("SantosRP", "Changelog", None))
        self.desiredserver.setText(_translate("SantosRP", "Desired server:", None))
        self.radio_eu.setText(_translate("SantosRP", "EU", None))
        self.radio_us.setText(_translate("SantosRP", "US", None))
        self.fileselect.setText(_translate("SantosRP", "...", None))
        self.credits1.setText(_translate("SantosRP", "COPYRIGHT © 2016 BY SANTOS ROLEPLAY", None))
        self.credits2.setText(_translate("SantosRP", "<a href=\"http://steamcommunity.com/id/187z/\" style=\"color:#FFF;text-decoration:none;\">LAUNCHER MADE BY BLUEDOG</a>", None))
        self.Players.setText(_translate("SantosRP", "Players:", None))

        self.btn_update.clicked.connect(self.updateFunc)
        self.fileselect.clicked.connect(self.getSvnDir)
        self.btn_lh.clicked.connect(self.viewChangeLog)
        self.radio_us.clicked.connect(self.playerCountUS)
        self.radio_eu.clicked.connect(self.playerCountEU)
        self.btn_play.clicked.connect(self.Play)
        self.btn_joinTS.clicked.connect(self.joinTS)



    def joinTS(self):
        webbrowser.open("ts3server://ts.santosrp.com?channel=Gspeak")

    def viewChangeLog(self):
        webbrowser.open("https://santosrp.com/forums/index.php?/forum/7-changelog/&%2Fforums%2Fforum%2F7-changelog%2F=")

    def playerCountUS(self):
        http = urllib3.PoolManager()
        usfile = http.request('GET', 'http://santosrp.com/PlayerCacheUSFile.txt')
        usplayercount = usfile.data
        self.playercount.setText(usplayercount)
        global srpsrv
        srpsrv = "steam://connect/167.114.214.130:27015"

    def playerCountEU(self):
        http = urllib3.PoolManager()
        eufile = http.request('GET', 'http://santosrp.com/PlayerCacheEUFile.txt')
        euplayercount = eufile.data
        self.playercount.setText(euplayercount)
        global srpsrv
        srpsrv = "steam://connect/51.255.119.141:27015"

    def Play(self):
        if srpsrv is None:
            print("no server selected")
            QtGui.QMessageBox.about(self, "Can't play... yet", "No server selected.")

        else:
            webbrowser.open(srpsrv)

    def getSvnDir(self):
        global svnDir
        svnFile = open('svninfo.txt', 'w+')
        svnDir = QtGui.QFileDialog.getExistingDirectory(self)
        self.filepath.setText(svnDir)
        svnFile.write(svnDir)


    def updateFunc(self):

        if svnDir is None:
            QtGui.QMessageBox.about(self, "Updating error", "No folder selected to update SVN!")
        else:
            path = svnDir
            if os.listdir(path) == []:
                QtGui.QMessageBox.about(self, "Updating", "No current content detected.\nFull download initiated.")
                srpsvn.checkout('http://svn.santosrp.com/svn/santosv2', 'content')
            else:
                try:
                    QtGui.QMessageBox.about(self, "Updating", "The update has started! \n \nThis program might go into not responding, please do not close this program, just minimize me!\n\nI'll let you know once the download is complete :) ")
                    srpsvn.update('content')
                except:
                    QtGui.QMessageBox.about(self, "Damnit", "Previous operation not finished!\nIniating cleanup....\n \nPlease press the update button again!")
                    srpsvn.cleanup(svnDir)

        QtGui.QMessageBox.about(self, "Completed", "Download completed!")

if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    ex = Ui_SantosRP()
    ex.show()
    sys.exit(app.exec_())

